In [53]:
#1

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score

# Załaduj zbiór danych Iris
dataset_iris = load_iris()

# Podziel zbiór danych na część treningową i walidacyjną
X_train, X_valid, y_train, y_valid = train_test_split(dataset_iris.data, dataset_iris.target, test_size=0.2, random_state=42)

# Inicjalizuj model KNeighborsRegressor z parametrem liczby sąsiadów równym 2
model = KNeighborsRegressor(n_neighbors=2)

# Trenuj model na części treningowej zbioru
model.fit(X_train, y_train)

# A. Wyznacz prognozowane klasy (y_prediction) za pomocą wytrenowanego modelu używając części walidacyjnej zbioru.
y_prediction = model.predict(X_valid)

# B. Wyświetl 15 pierwszych prognozowanych klas i porównaj z pierwszymi 15 wartościami ze zbioru walidacyjnego (y_valid)
print("Pierwsze 15 prognozowanych klas:")
print(y_prediction[:15])
print("Pierwsze 15 wartości ze zbioru walidacyjnego:")
print(y_valid[:15])

# C. Używając walidacyjnej części zbioru wyznacz dokładność (accuracy) dla przygotowanego modelu.
accuracy = accuracy_score(y_valid, y_prediction.round())
# D. Zinterpretuj uzyskaną dokładność
# Wartości docelowe dla zbioru Iris są liczbami całkowitymi odpowiadającymi klasom: 0, 1 lub 2.
# Dokładność to stosunek poprawnych prognoz do wszystkich prognoz.

print("Dokładność modelu: {:.2f}%".format(accuracy * 100))

# E. Porównaj dokładność wyznaczoną dla zbioru walidacyjnego i dla zbioru treningowego
# Dokładność dla zbioru treningowego może być wyższa niż dla zbioru walidacyjnego, jeśli model został przeuczony na danych treningowych.
# Niższa dokładność dla zbioru walidacyjnego może wskazywać na zjawisko przeuczenia.
# Dlatego ważne jest monitorowanie zarówno dokładności zbioru treningowego, jak i walidacyjnego.

y_train_pred = model.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_pred.round())
print("Dokładność dla zbioru treningowego: {:.2f}%".format(train_accuracy * 100))


Pierwsze 15 prognozowanych klas:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0]
Pierwsze 15 wartości ze zbioru walidacyjnego:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0]
Dokładność modelu: 100.00%
Dokładność dla zbioru treningowego: 96.67%


In [7]:
#1 V.
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor


# Załaduj zbiór danych Iris
dataset_iris = load_iris()

X_train, X_test, y_train, y_test = train_test_split(dataset_iris.data, dataset_iris.target, test_size=0.2, random_state=42)
model = KNeighborsRegressor(n_neighbors=2)
model.fit(X_train, y_train)

y_prediction = model.predict(X_test)
print(y_prediction[:10])
print(y_test[:10])

[1. 0. 2. 1. 1. 0. 1. 2. 1. 1.]
[1 0 2 1 1 0 1 2 1 1]


In [9]:
#2

from sklearn.metrics import precision_score, recall_score, f1_score, matthews_corrcoef, confusion_matrix, classification_report

# A. Precyzja klasyfikacji
precision = precision_score(y_test, y_prediction.round(), average='weighted')
print("Precyzja klasyfikacji: {:.2f}".format(precision))

# B. Czułość klasyfikacji
recall = recall_score(y_test, y_prediction.round(), average='weighted')
print("Czułość klasyfikacji: {:.2f}".format(recall))

# C. F1-score i współczynnik Mathewsa
f1 = f1_score(y_test, y_prediction.round(), average='weighted')
matthews = matthews_corrcoef(y_test, y_prediction.round())
print("F1-score: {:.2f}".format(f1))
print("Współczynnik Mathewsa: {:.2f}".format(matthews))

# D. Macierz pomyłek
conf_matrix = confusion_matrix(y_test, y_prediction.round())
print("Macierz pomyłek:")
print(conf_matrix)

# E. Raport klasyfikacji
classification_rep = classification_report(y_test, y_prediction.round())
print("Raport klasyfikacji:")
print(classification_rep)

Precyzja klasyfikacji: 1.00
Czułość klasyfikacji: 1.00
F1-score: 1.00
Współczynnik Mathewsa: 1.00
Macierz pomyłek:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Raport klasyfikacji:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [3]:
#3
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error

# Załaduj zbiór danych diabetes
diabetes = load_diabetes()

# Podziel zbiór danych na część treningową i walidacyjną
X_train, X_valid, y_train, y_valid = train_test_split(diabetes.data, diabetes.target, train_size=250)

# Inicjalizuj model KNeighborsRegressor z parametrem liczby sąsiadów równym 2
model = KNeighborsRegressor(n_neighbors=2)

# Trenuj model na części treningowej zbioru
model.fit(X_train, y_train)

# A. Wyznacz prognozy (y_prediction) za pomocą wytrenowanego modelu używając części walidacyjnej zbioru
y_prediction = model.predict(X_valid)

# B. Wyświetl 10 pierwszych prognoz i porównaj z pierwszymi 10 wartościami ze zbioru walidacyjnego (y_valid)
print("Pierwsze 10 prognoz:")
print(y_prediction[:10])
print("Pierwsze 10 wartości ze zbioru walidacyjnego:")
print(y_valid[:10])

# C. Używając walidacyjnej części zbioru wyznacz średni błąd bezwzględny - MAE (mean absolute error) dla przygotowanego modelu
mae = mean_absolute_error(y_valid, y_prediction)
print("Średni błąd bezwzględny (MAE): {:.2f}".format(mae))

# D. Zinterpretuj wyznaczony błąd
# Wartości docelowe dla zbioru diabetes są kontynuacyjne, reprezentując progresję choroby.
# Średni błąd bezwzględny mierzy średnią wartość bezwzględną różnicy między rzeczywistymi a prognozowanymi wartościami.
# Im niższy MAE, tym lepiej model przewiduje wartości docelowe.

# E. Porównaj średni błąd bezwzględny wyznaczony dla zbioru walidacyjnego i dla zbioru treningowego
# Różnica między MAE dla zbioru treningowego a walidacyjnego może wskazywać na to, czy model jest przeuczony lub niedotrenowany.
# Należy monitorować oba MAE, aby zrozumieć ogólną wydajność modelu.
y_train_pred = model.predict(X_train)
train_mae = mean_absolute_error(y_train, y_train_pred)
print("Średni błąd bezwzględny dla zbioru treningowego: {:.2f}".format(train_mae))


Pierwsze 10 prognoz:
[134.  128.5 116.   92.5 101.5 146.5 202.   94.5  78.  206. ]
Pierwsze 10 wartości ze zbioru walidacyjnego:
[225. 102. 182.  83. 220. 113. 151.  96.  72. 191.]
Średni błąd bezwzględny (MAE): 51.13
Średni błąd bezwzględny dla zbioru treningowego: 32.29


In [10]:
#4

from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, r2_score
import numpy as np

# Załaduj zbiór danych diabetes
diabetes = load_diabetes()

# Podziel zbiór danych na część treningową i walidacyjną
X_train, X_valid, y_train, y_valid = train_test_split(diabetes.data, diabetes.target, train_size=250)


# A. Błąd średniokwadratowy - MSE
mse = mean_squared_error(y_valid, y_prediction)
print("Błąd średniokwadratowy (MSE): {:.2f}".format(mse))

# B. Podstawowy błąd średniokwadratowy - RMSE
rmse = np.sqrt(mse)
print("Podstawowy błąd średniokwadratowy (RMSE): ", rmse)

# C. Średni bezwzględny błąd procentowy - MAPE
# Pamiętaj, żeby uniknąć dzielenia przez zero, wartości prognozowane muszą być różne od zera.
# W przeciwnym razie mogą być obciążone, co wpłynie na MAPE.
mape = mean_absolute_percentage_error(y_valid, y_prediction)
print("Średni bezwzględny błąd procentowy (MAPE): ", mape)

# D. Współczynnik determinacji - R^2
r_squared = r2_score(y_valid, y_prediction)
print("Współczynnik determinacji (R^2): ", r_squared)


Błąd średniokwadratowy (MSE): 9578.51
Podstawowy błąd średniokwadratowy (RMSE):  97.86987800561178
Średni bezwzględny błąd procentowy (MAPE):  0.7292934150332533
Współczynnik determinacji (R^2):  -0.70343455754676


In [39]:
#1v

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
#from sklearn.metrics import

dataset_iris = load_iris()

X_train, X_valid, y_train, y_valid = train_test_split(dataset_iris.data, dataset_iris.target, test_size=0.2, random_state=42)

model = KNeighborsRegressor(n_neighbors=2)

model.fit(X_train, y_train)

y_prediction = model.predict(X_valid)

print("Pierwsze 15 prognozowanych klas: ")
print(y_prediction[:15])
print("Pierwsze 15 wartosci ze zbioru walidacyjnego: ")
print(y_valid[:15])

accuracy = accuracy_score(y_valid, y_prediction.round())
print("Celnosc naszego modelu dla zbioru walidacyjnego: {:.2f}%".format(accuracy*100))

train_y_prediction = model.predict(X_train)
t_accuracy = accuracy_score(y_train, train_y_prediction.round())
print("Celnosc naszego modelu dla zbioru treningowego: {:.2f}%".format(t_accuracy*100))

Pierwsze 15 prognozowanych klas: 
[1. 0. 2. 1. 1. 0. 1. 2. 1. 1. 2. 0. 0. 0. 0.]
Pierwsze 15 wartosci ze zbioru walidacyjnego: 
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0]
Celnosc naszego modelu dla zbioru walidacyjnego: 100.00%
Celnosc naszego modelu dla zbioru treningowego: 97.50%


In [52]:
#2v

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, matthews_corrcoef, confusion_matrix, classification_report

precision = precision_score(y_valid, y_prediction.round(), average='weighted')
print("Precyzja: ", precision*100,"%")

recall = recall_score(y_valid, y_prediction.round(), average='weighted')
print("Czulosc: ", recall*100,"%")

f1 = f1_score(y_valid, y_prediction.round(), average='weighted')
print("F1: ", f1*100,"%")

mat = matthews_corrcoef(y_valid, y_prediction.round())
print("Matthews: ", mat*100,"%")

macpom = confusion_matrix(y_valid, y_prediction.round())
print(macpom)

report = classification_report(y_valid, y_prediction.round())
print("Raport")
print(report)

Precyzja:  100.0 %
Czulosc:  100.0 %
F1:  100.0 %
Matthews:  100.0 %
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Raport
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [66]:
#3v
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error

diabetes = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(diabetes.data, diabetes.target, train_size=250)

model = KNeighborsRegressor(n_neighbors=2)
model.fit(X_train, y_train)

#A 
y_prediction = model.predict(X_test)
#B
print(y_prediction[:10])
print(y_test[:10])
#C, D - wytlumacz
mae = mean_absolute_error(y_test, y_prediction)

print("MAE: ", mae)
print(diabetes.target[:5])

#E
y_train_pred = model.predict(X_train)
mae_t = mean_absolute_error(y_train, y_train_pred)

print("MAE:")
print(mae)
print(mae_t)

[226.  175.5  63.5 161.5 194.  181.  213.5 243.   55.  128.5]
[150.  55. 116.  73.  84.  81.  89. 189.  77.  68.]
MAE:  47.299479166666664
[151.  75. 141. 206. 135.]
MAE:
47.299479166666664
36.566


In [74]:
#4v
#DLA ZBIORU VALIDACYJNEGO - TEST
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, r2_score
import numpy as np

mse = mean_squared_error(y_test, y_prediction)
rmse = np.sqrt(mse)
mape = mean_absolute_percentage_error(y_test, y_prediction)
r2 = r2_score(y_test, y_prediction)



In [25]:
#6
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_classification

X_bin, y_bin = make_classification(n_samples=500, n_features=5, n_classes=2)

X_train, X_test, y_train, y_test = train_test_split(X_bin, y_bin, test_size=0.2, random_state=42)

object = KNeighborsRegressor(n_neighbors=2)
object.fit(X_train, y_train)

y_prediction = object.predict(X_test)

acc = accuracy_score(y_test, y_prediction.round())

print(y_test[:15])
print(y_prediction[:15])

print(acc*100, "%")

y_train_prediction = object.predict(X_train)
train_acc = accuracy_score(y_train, y_train_prediction.round())

print("Dokladnosc dla danych walidacyjnych:")
print(acc*100, "%")
print("Dokladnosc dla danych testowych:")
print(train_acc*100, "%")

[1 1 1 1 1 1 0 0 1 0 0 0 0 0 1]
[0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
86.0 %
Dokladnosc dla danych walidacyjnych:
86.0 %
Dokladnosc dla danych testowych:
95.75 %


In [12]:
#3vv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error
import numpy as np

diabetes = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(diabetes.data, diabetes.target, train_size=250)
model = KNeighborsRegressor(n_neighbors=2)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)

y_t_pred = model.predict(X_train)
tmae = mean_absolute_error(y_train, y_t_pred)

print(mae)
print(tmae)

52.5546875
30.326


In [18]:
#4vv
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, r2_score

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mape = mean_absolute_percentage_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

In [ ]:
#9
from sklearn.datasets import make_regression
from sklearn.
from sklearn.

X_reg2, y_reg2 = make_regression(n_samples=600, n_features=6) #zbior z z6l3

X_train, X_test, y_train, y_test = train_test_split(X_reg2, y_reg2, test_size=0.2, random_state=42)
model = KN